name: solara_py310
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - pip=25.2
  - python-dotenv=1.1.1
  - uvicorn=0.35.0
  - pip:
    - solara==1.51.1
    - pandas==2.3.2
    - requests==2.32.5
    - httpx==0.28.1